app_group:
  - read:
      path: /apps/nats.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}/_targets
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}/_targets
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}/_targets
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}/_topology
      method: POST
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}/_topology
      method: POST
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}/_topology
      method: POST
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}/_topology
      method: POST

patch:
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}
      method: PATCH
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}
      method: PATCH
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}
      method: PATCH
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}/_revs
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}/_revs
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}/_revs
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}/_topology
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}/_topology
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}/_topology
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}
      method: DELETE
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}
      method: DELETE
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}
      method: DELETE
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.nats.v1alpha1.cluster_export:
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports
      method: POST
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}
      method: GET
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/{name}
      method: PUT

com.nokia.eda.nats.v1alpha1.cluster_export_list:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports
      method: GET
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports
      method: DELETE

com.nokia.eda.nats.v1alpha1.cluster_export_deleted_resources:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterexports/_deleted
      method: GET

com.nokia.eda.nats.v1alpha1.cluster_publisher:
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers
      method: POST
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}
      method: GET
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/{name}
      method: PUT

com.nokia.eda.nats.v1alpha1.cluster_publisher_list:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers
      method: GET
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers
      method: DELETE

com.nokia.eda.nats.v1alpha1.cluster_publisher_deleted_resources:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/clusterpublishers/_deleted
      method: GET

com.nokia.eda.nats.v1alpha1.export:
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports
      method: POST
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}
      method: GET
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/{name}
      method: PUT

com.nokia.eda.nats.v1alpha1.export_list:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/exports
      method: GET
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports
      method: GET
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports
      method: DELETE

com.nokia.eda.nats.v1alpha1.export_deleted_resources:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/exports/_deleted
      method: GET

com.nokia.eda.nats.v1alpha1.publisher:
  - create:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers
      method: POST
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}
      method: GET
  - update:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/{name}
      method: PUT

com.nokia.eda.nats.v1alpha1.publisher_list:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers
      method: GET
  - delete:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers
      method: DELETE
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/publishers
      method: GET

com.nokia.eda.nats.v1alpha1.publisher_deleted_resources:
  - read:
      path: /apps/nats.eda.nokia.com/v1alpha1/namespaces/{namespace}/publishers/_deleted
      method: GET

totalPaths: 29
totalSchemas: 75
usedSchemas: 21
unusedSchemas: 54
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.nats.v1alpha1.ClusterExport_DeletedResourceEntry
  - com.nokia.eda.nats.v1alpha1.ClusterExport_alarms
  - com.nokia.eda.nats.v1alpha1.ClusterExport_deviations
  - com.nokia.eda.nats.v1alpha1.ClusterExport_metadata
  - com.nokia.eda.nats.v1alpha1.ClusterPublisher_DeletedResourceEntry
  - com.nokia.eda.nats.v1alpha1.ClusterPublisher_alarms
  - com.nokia.eda.nats.v1alpha1.ClusterPublisher_deviations
  - com.nokia.eda.nats.v1alpha1.ClusterPublisher_metadata
  - com.nokia.eda.nats.v1alpha1.Export_DeletedResourceEntry
  - com.nokia.eda.nats.v1alpha1.Export_alarms
  - com.nokia.eda.nats.v1alpha1.Export_deviations
  - com.nokia.eda.nats.v1alpha1.Export_metadata
  - com.nokia.eda.nats.v1alpha1.Publisher_DeletedResourceEntry
  - com.nokia.eda.nats.v1alpha1.Publisher_alarms
  - com.nokia.eda.nats.v1alpha1.Publisher_deviations
  - com.nokia.eda.nats.v1alpha1.Publisher_metadata
